/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author kouss
 */
public class SecretaryUI extends javax.swing.JFrame {

    /**
     * Creates new form SecretaryUI
     */
    public SecretaryUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtApproveUsername = new javax.swing.JTextField();
        txtApprovePassword = new javax.swing.JTextField();
        txtApproveSurname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtApproveFirstname = new javax.swing.JTextField();
        txtApproveAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnApprovePatient = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtApproveGender = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtApproveAge = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listApprovePatient = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnRemovePatient = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        listPatients = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listPatientTerminate = new javax.swing.JList<>();
        jLabel16 = new javax.swing.JLabel();
        txtRemoveUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        listPendingAppointments = new javax.swing.JList<>();
        jLabel46 = new javax.swing.JLabel();
        txtUserStart = new javax.swing.JTextField();
        txtRequestDoctor = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        txtPatientApp = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        txtAppResponse = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        boxDoctor = new javax.swing.JComboBox<>();
        jLabel52 = new javax.swing.JLabel();
        btnCreateAppointment = new javax.swing.JButton();
        txtAppointmentID = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        lbPatientID = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSecretaryID = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Approve user Accounts"));

        txtApproveUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApproveUsernameActionPerformed(evt);
            }
        });

        txtApprovePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApprovePasswordActionPerformed(evt);
            }
        });

        jLabel2.setText("Password");

        jLabel3.setText("Firstname");

        jLabel4.setText("Surname");

        txtApproveAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApproveAddressActionPerformed(evt);
            }
        });

        jLabel5.setText("Address");

        btnApprovePatient.setText("Approve");
        btnApprovePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApprovePatientActionPerformed(evt);
            }
        });

        jLabel6.setText("Click to view user");

        txtApproveGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApproveGenderActionPerformed(evt);
            }
        });

        jLabel7.setText("Gender");

        txtApproveAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApproveAgeActionPerformed(evt);
            }
        });

        jLabel8.setText("Age");

        jLabel9.setText("Make sure fields are correct and click approve");

        jLabel10.setText("Username");

        listApprovePatient.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listApprovePatient);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnApprovePatient))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtApproveAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                    .addComponent(txtApproveGender)
                                    .addComponent(txtApproveAge)
                                    .addComponent(txtApproveSurname)
                                    .addComponent(txtApproveFirstname)
                                    .addComponent(txtApprovePassword)
                                    .addComponent(txtApproveUsername)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApproveUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApprovePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtApproveFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtApproveSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtApproveAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtApproveGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtApproveAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnApprovePatient)
                .addGap(19, 19, 19))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Remove Patients"));

        btnRemovePatient.setText("Delete");
        btnRemovePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemovePatientActionPerformed(evt);
            }
        });

        listPatients.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listPatients.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listPatients.setToolTipText("");
        jScrollPane4.setViewportView(listPatients);

        jLabel15.setText("request account termination");

        jLabel18.setText("Make sure username is correct and click remove");

        listPatientTerminate.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listPatientTerminate.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listPatientTerminate.setToolTipText("");
        jScrollPane5.setViewportView(listPatientTerminate);

        jLabel16.setText("All Patients");

        jLabel1.setText("Username");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRemoveUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel18))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btnRemovePatient)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRemoveUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemovePatient)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Create Appointment"));

        listPendingAppointments.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listPendingAppointments.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listPendingAppointments.setToolTipText("");
        jScrollPane8.setViewportView(listPendingAppointments);

        jLabel46.setText("Date");

        txtUserStart.setEditable(false);
        txtUserStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserStartActionPerformed(evt);
            }
        });

        txtRequestDoctor.setEditable(false);

        jLabel47.setText(" date");

        jLabel49.setText("requested Doctor");

        txtPatientApp.setEditable(false);

        jLabel50.setText("Patient");

        txtAppResponse.setEditable(false);
        txtAppResponse.setForeground(new java.awt.Color(255, 0, 0));
        txtAppResponse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAppResponseActionPerformed(evt);
            }
        });

        jLabel51.setText("Response");

        jLabel52.setText("Doctor");

        btnCreateAppointment.setText("Create Appointment");

        txtAppointmentID.setEditable(false);
        txtAppointmentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAppointmentIDActionPerformed(evt);
            }
        });

        jLabel55.setText("Appointment ID");

        jLabel42.setText("Create New Appointment");

        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        jLabel43.setText("Set date such as 09/10");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel55)
                            .addComponent(jLabel47))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUserStart, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAppointmentID, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel49)
                            .addComponent(jLabel50)
                            .addComponent(jLabel51))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPatientApp, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(txtRequestDoctor)
                            .addComponent(txtAppResponse)))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCreateAppointment)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel52)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(boxDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel46)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtDate))
                                .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(22, 22, 22)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAppointmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel55))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUserStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel47))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel49)
                            .addComponent(txtRequestDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPatientApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel50))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel51)
                            .addComponent(txtAppResponse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(boxDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateAppointment)
                .addContainerGap())
        );

        lbPatientID.setText("Secretary ID");

        jScrollPane2.setViewportView(txtSecretaryID);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbPatientID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPatientID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApproveAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApproveAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApproveAgeActionPerformed

    private void txtApproveGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApproveGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApproveGenderActionPerformed

    private void btnApprovePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApprovePatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnApprovePatientActionPerformed

    private void txtApproveAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApproveAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApproveAddressActionPerformed

    private void btnRemovePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemovePatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemovePatientActionPerformed

    private void txtAppResponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAppResponseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAppResponseActionPerformed

    private void txtAppointmentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAppointmentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAppointmentIDActionPerformed

    private void txtUserStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserStartActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void txtApproveUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApproveUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApproveUsernameActionPerformed

    private void txtApprovePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApprovePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApprovePasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecretaryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecretaryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecretaryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecretaryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecretaryUI().setVisible(true);
            }
        });
    }
     /**
     *
     * @return
     */
    public String getTxtSecretaryID() {
        return txtSecretaryID.getText();
    }

    /**
     *
     * @param txtSecretaryID
     */
    public void setTxtSecretaryID(String txtSecretaryID) {
        this.txtSecretaryID.setText(txtSecretaryID);
    }
    
    //Approve Patient

    /**
     *
     * @param listener
     */
    public void btnApprovePatient(ActionListener listener){
        this.btnApprovePatient.addActionListener(listener);
    }

    /**
     *
     * @param listener
     */
    public void listApprovePatientListener(ListSelectionListener listener){
        this.listApprovePatient.addListSelectionListener(listener);
    }

    /**
     *
     * @return
     */
    public String getListApprovePatient() {
        return listApprovePatient.getSelectedValue();
    }

    /**
     *
     * @param listApprovePatient
     */
    public void setListApprovePatient(String[] listApprovePatient) {
        this.listApprovePatient.setListData(listApprovePatient);
    }

    /**
     *
     * @return
     */
    public String getTxtApproveAddress() {
        return txtApproveAddress.getText();
    }

    /**
     *
     * @param txtApproveAddress
     */
    public void setTxtApproveAddress(String txtApproveAddress) {
        this.txtApproveAddress.setText(txtApproveAddress);
    }

    /**
     *
     * @return
     */
    public String getTxtApproveAge() {
        return txtApproveAge.getText();
    }

    /**
     *
     * @param txtApproveAge
     */
    public void setTxtApproveAge(String txtApproveAge) {
        this.txtApproveAge.setText(txtApproveAge);
    }

    /**
     *
     * @return
     */
    public String getTxtApproveFirstname() {
        return txtApproveFirstname.getText();
    }

    /**
     *
     * @param txtApproveFirstname
     */
    public void setTxtApproveFirstname(String txtApproveFirstname) {
        this.txtApproveFirstname.setText(txtApproveFirstname);
    }

    /**
     *
     * @return
     */
    public String getTxtApproveGender() {
        return txtApproveGender.getText();
    }

    /**
     *
     * @param txtApproveGender
     */
    public void setTxtApproveGender(String txtApproveGender) {
        this.txtApproveGender.setText(txtApproveGender);
    }

    /**
     *
     * @return
     */
    public String getTxtApprovePassword() {
        return txtApprovePassword.getText();
    }

    /**
     *
     * @param txtApprovePassword
     */
    public void setTxtApprovePassword(String txtApprovePassword) {
        this.txtApprovePassword.setText(txtApprovePassword);
    }

    /**
     *
     * @return
     */
    public String getTxtApproveSurname() {
        return txtApproveSurname.getText();
    }

    /**
     *
     * @param txtApproveSurname
     */
    public void setTxtApproveSurname(String txtApproveSurname) {
        this.txtApproveSurname.setText(txtApproveSurname);
    }

    /**
     *
     * @return
     */
    public String getTxtApproveUsername() {
        return txtApproveUsername.getText();
    }

    /**
     *
     * @param txtApproveUsername
     */
    public void setTxtApproveUsername(String txtApproveUsername) {
        this.txtApproveUsername.setText(txtApproveUsername);
    }
    
    //remove patient

    /**
     *
     * @param listener
     */
    public void btnRemovePatient(ActionListener listener){
        this.btnRemovePatient.addActionListener(listener);
    }

    /**
     *
     * @param listener
     */
    public void listPatientListener(ListSelectionListener listener){
        this.listPatients.addListSelectionListener(listener);
    }

    /**
     *
     * @param listener
     */
    public void listTermiatePatientListener(ListSelectionListener listener){
        this.listPatientTerminate.addListSelectionListener(listener);
    }
    
    /**
     *
     * @return
     */
    public String getListPatientTerminate() {
        return listPatientTerminate.getSelectedValue();
    }

    /**
     *
     * @param listPatientTerminate
     */
    public void setListPatientTerminate(String[] listPatientTerminate) {
        this.listPatientTerminate.setListData(listPatientTerminate);
    }

    /**
     *
     * @return
     */
    public String getListPatients() {
        return listPatients.getSelectedValue();
    }

    /**
     *
     * @param listPatients
     */
    public void setListPatients(String[] listPatients) {
        this.listPatients.setListData(listPatients);
    }

    /**
     *
     * @return
     */
    public String getTxtRemoveUsername() {
        return txtRemoveUsername.getText();
    }

    /**
     *
     * @param txtRemoveUsername
     */
    public void setTxtRemoveUsername(String txtRemoveUsername) {
        this.txtRemoveUsername.setText(txtRemoveUsername);
    }
    
    /**
     *
     */
    public void deselectPatientList(){
        this.listPatients.clearSelection();
    }

    /**
     *
     */
    public void deselectPatientTerminateList(){
        this.listPatientTerminate.clearSelection();
    }

    // to add appointments

    /**
     *
     * @param listener
     */
    public void listPendingAppointmentsonClick(ListSelectionListener listener){
        this.listPendingAppointments.addListSelectionListener(listener);
    }

    /**
     *
     * @return
     */
    public String getListPendingAppointments() {
        return listPendingAppointments.getSelectedValue();
    }

    /**
     *
     * @param listPendingAppointments
     */
    public void setListPendingAppointments(String[] listPendingAppointments) {
        this.listPendingAppointments.setListData(listPendingAppointments);
    }

    /**
     *
     * @return
     */
    public String getBoxDoctor() {
        return (String) boxDoctor.getSelectedItem();
    }

    /**
     *
     * @param boxDoctor
     */
    public void addBoxDoctor(String boxDoctor) {
        this.boxDoctor.addItem(boxDoctor);
    }


    /**
     *
     * @return
     */
    public String getTxtPatientApp() {
        return txtPatientApp.getText();
    }

    /**
     *
     * @param txtPatientApp
     */
    public void setTxtPatientApp(String txtPatientApp) {
        this.txtPatientApp.setText(txtPatientApp);
    }



    /**
     *
     * @return
     */
    public String getTxtUserStart() {
        return txtUserStart.getText();
    }

    /**
     *
     * @param txtUserStart   */
    public void setTxtUserStart(String txtUserStart) {
        this.txtUserStart.setText(txtUserStart);
    }

    /**
     *
     @return 
     */
    public String getTxtRequestDoctor() {
        return txtRequestDoctor.getText();
    }

    /**
     *
     * @param txtRequestDoctor
     */
    public void setTxtRequestDoctor(String txtRequestDoctor) {
        this.txtRequestDoctor.setText(txtRequestDoctor);
    }

    /**
     *
     * @param listener
     */
    public void btnCreateAppointmentListener(ActionListener listener){
        this.btnCreateAppointment.addActionListener(listener);
    }

    /**
     *
     * @return
     */
    public String getTxtAppointmentID() {
        return txtAppointmentID.getText();
    }

    /**
     *
     * @param txtAppointmentID
     */
    public void setTxtAppointmentID(String txtAppointmentID) {
        this.txtAppointmentID.setText(txtAppointmentID);
    }

    /**
     *
     */
    public void deselectPendingAppointment(){
        this.listPendingAppointments.clearSelection();
    }
    
        /**
     *
     * @param txtAppResponse
     */
    public void setTxtAppResponse(String txtAppResponse) {
        this.txtAppResponse.setText(txtAppResponse);
    }
    
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxDoctor;
    private javax.swing.JButton btnApprovePatient;
    private javax.swing.JButton btnCreateAppointment;
    private javax.swing.JButton btnRemovePatient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel lbPatientID;
    private javax.swing.JList<String> listApprovePatient;
    private javax.swing.JList<String> listPatientTerminate;
    private javax.swing.JList<String> listPatients;
    private javax.swing.JList<String> listPendingAppointments;
    private javax.swing.JTextField txtAppResponse;
    private javax.swing.JTextField txtAppointmentID;
    private javax.swing.JTextField txtApproveAddress;
    private javax.swing.JTextField txtApproveAge;
    private javax.swing.JTextField txtApproveFirstname;
    private javax.swing.JTextField txtApproveGender;
    private javax.swing.JTextField txtApprovePassword;
    private javax.swing.JTextField txtApproveSurname;
    private javax.swing.JTextField txtApproveUsername;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtPatientApp;
    private javax.swing.JTextField txtRemoveUsername;
    private javax.swing.JTextField txtRequestDoctor;
    private javax.swing.JTextPane txtSecretaryID;
    private javax.swing.JTextField txtUserStart;
    // End of variables declaration//GEN-END:variables
}
